### ISSUE TITLE
The way to calculate 'near' is confusing

### ISSUE THREAD

**Issue by OceanYing** [google/nerfies#10]
Very appreciative for the release. I noticed that the way you calculate 'near' is confusing, in **Nerfies_Capture_Processing.ipynb**, under the part called **Compute Scene Information**, .
```
near = near_far['near'].quantile(0.001) / 0.8
```
I run it and found that some area of the face points were cut off by the **near** value. See the points beyond the purple near plane in this image:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/37448328/109802900-52ec0600-7c5b-11eb-93eb-650be20512e5.png">

Since the 'depths' you used are positive, maybe it should be like this?
```
near = near_far['near'].quantile(0.001) * 0.8
```

**Comment by keunhong** [comment]
Hi yes, it's just a hacky heuristic to compute the near plane somewhat automatically.
