### ISSUE TITLE
orientation render video

### ISSUE THREAD

**Issue by ccimarp1990** [google/nerfies#12]
How can I change the orientation of the render video?

**Comment by keunhong** [comment]
You will have to generate your own test cameras (for the Colab demo it's done [here](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb#scrollTo=w6CqOeEkbrcK&line=1&uniqifier=1). You can modify the test camera generation with a different orientation.
