### ISSUE TITLE
How to install required packages?

### ISSUE THREAD

**Issue by zeitphase** [google/nerfies#14]
Hi, I'm trying to get the code run on my Mac (might not work since there is no cuda support in Mojave) but I'm still wondering what to do next.
So far I have installed Miniconda and installed the environment with 
  conda create --name nerfies python=3.8

Next step is to install the required packages with
  pip install -r requirements.txt

Where exactly do I execute this install command?

**Comment by keunhong** [comment]
Hi,

Check out the [official docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) and [this blog post](https://towardsdatascience.com/getting-started-with-python-environments-using-conda-32e9f2779307?gi=1abbb8947e69).

You need to activate the environment by doing this first:

    conda activate nerfies
