### ISSUE TITLE
train loss becomes nan

### ISSUE THREAD

**Issue by Carinazhao22** [google/nerfies#15]
Hi, while I am training my data locally, the loss becomes nan. What are the possible reasons?  Thank you!  
![b63c8a64498a8caa91e9c9f85adea6d](https://user-images.githubusercontent.com/52422263/112743572-4b173d00-8f4d-11eb-8f4e-a4e094d92d45.jpg)

**Comment by keunhong** [comment]
Can you try disabling or weakening the elastic loss?

**Comment by Carinazhao22** [comment]
got it. Thank you!
