### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nav74neet** [google/nerfies#17]
Hi, while trying to execute the "Create training iterators" under the Nerfies Training.ipynb colab notebook, I'm facing the following issue:
![nerfies_train](https://user-images.githubusercontent.com/33291299/115129330-375b7580-9fe5-11eb-93a8-aa51563a80f8.png)
Is it the issue with setting the runtime as TPU or JAX version compatibility?

**Comment by keunhong** [comment]
Have you generated the `metadata.json` file in the dataset creation Colab?

**Comment by nav74neet** [comment]
yes, I have already executed the data creation Colab notebook prior to starting the training one.
