### ISSUE TITLE
TypeError: reshape total size must be unchanged

### ISSUE THREAD

**Issue by nav74neet** [google/nerfies#18]
Hi, while training  using google colab, I'm facing the following Type Error:
![trainig_error](https://user-images.githubusercontent.com/33291299/115753778-d7c1e900-a39b-11eb-85d6-14e0c3f720c0.png)
What could be the reason? and possible solutions please.

**Comment by keunhong** [comment]
Can you try padding the input images to be divisible by 2?

**Comment by keunhong** [comment]
Hi closing since it's been a while. Feel free to re-open if it's still an issue.
