### ISSUE TITLE
Error with Nerfies configuration in "Nerfies Render Video.ipynb".

### ISSUE THREAD

**Issue by SaukVA** [google/nerfies#19]
Hi, I have been using your Google Colab notebooks for several days. They were working fine but yesterday I tried to use "Nerfies Render Video.ipynb" and I got this error: 

![image](https://user-images.githubusercontent.com/32059615/116998120-0a45dd00-acde-11eb-880a-1b7454a40f99.png)

I have tried changing the "train_dir:" and "data_dir:", but I still get the same error. Any ideas on how to solve this problem?

**Comment by alexbarnadas** [comment]
Hey! I have the same problem. I thought it could be because I shut down my computer between the training and the rendering. But the checkpoints are saved, so it does not make much sense anyways. Please help!

**Comment by RodneyPerhaps** [comment]
!pip install frozendict==1.2 ipyplot flax==0.3.0
!pip install git+https://github.com/google/nerfies
Reinstall dependencies and rebuild nerfies work.

**Comment by SaukVA** [comment]
It is already working, thank you very much!

**Comment by keunhong** [comment]
Hi this should be fixed now.
