### ISSUE TITLE
Questions about face processing section in Colab

### ISSUE THREAD

**Issue by jiejie22997** [google/nerfies#2]
Hi, thanks for releasing the codes.

In Colab, process a video into a Nerfie dataset, it seems that the face processing section is optional. I skipped this section and ran compute scene information section. It gives errors, "name 'new_scene_manager' is not defined' ". 'new_scene_manager' is defined in face processing section. Is it necessary to run the face processing section or did I miss anything? 

![WeChat Image_20210204220139](https://user-images.githubusercontent.com/78582888/106995825-9757b500-6734-11eb-8dc2-3327ddc59982.jpg)

Thank you!

**Comment by keunhong** [comment]
Hi, if you'd like to skip the face processing, run
`new_scene_manager = scene_manager` and then you'll have to compute your own near/far values as well as the scene scale.

**Comment by jiejie22997** [comment]
hi, thanks for your fast response. 
I still have some questions. What is near/far value, and how can I calculate these? Is it anywhere in the colmap data? thanks

**Comment by keunhong** [comment]
You can use the pointcloud from SfM and the camera positions to compute the near/far planes.
Actually the Colab already does that, and it doesn't depend on the face stuff.
You can also plot the scene and set the near/far plane by hand if it doesn't seem to be doing the right thing.

**Comment by jiejie22997** [comment]
Thank you!  I understand it.

**Comment by kurtjcu** [comment]
Hi @jiejie22997 did you find a suitable method for generating or extracting the scene.json without faces?

**Comment by keunhong** [comment]
Hi, I have made the face processing part completely optional by generating camera trajectories without the facial landmarks. Please let me know if you have issues. Thanks!
