### ISSUE TITLE
Rendering results are strange

### ISSUE THREAD

**Issue by RodneyPerhaps** [google/nerfies#20]
In training process, predicted RGB of validation dataset is fine. 
![2021-05-07 10-03-44 的屏幕截图](https://user-images.githubusercontent.com/78194960/117387573-b4f70f00-af1b-11eb-8892-5d5b07ce3262.png)
But when rendering with the latest checkpoint, I got the strange results as follows:
![2021-05-07 10-06-18 的屏幕截图](https://user-images.githubusercontent.com/78194960/117387689-e66fda80-af1b-11eb-8c3c-d38d587f46b9.png)

**Comment by alexbarnadas** [comment]
It is optimized for human faces, but if I wanted to do it with an object I'd choose an object that did not produce aliasing. something without patterns. Thanks for your answer on last question, it worked for me ;)))))

**Comment by keunhong** [comment]
It is probably an issue with the cameras you are using to render the test views.

**Comment by Leviosaaaa** [comment]
I got the similar strange output. I guess the strange blue rendering frames @RodneyPerhaps got are the output of `test`, which as @keunhong pointed out was the rendering frames at novel test camera poses generated when pre-processing the dataset.

My question is: although the novel test camera poses may be unseen, the rendering frame is still generated using a seemingly well-trained model of the scene; shouldn't it still look like a tilted or zoomed image of the scene (maybe a little blurry)? But the output seems completely irrelevant to the scene; what may be the reason?

I would appreciate any insight. Thank you in advance!

**Comment by keunhong** [comment]
I've updated the codebase and Colabs to generate cameras using a different method, can you try that out? I think the output cameras should be better now.
