### ISSUE TITLE
pip install -r requirements.txt  - is faulty: minor error

### ISSUE THREAD

**Issue by xvdp** [google/nerfies#25]
Installation requirements, needs minor fix. 
I presume that 2.5 will work as well, but in the interest of neatness - installation scripts oughtn't fail. 

FYI

pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow==2.4.0

**Comment by keunhong** [comment]
I believe this should be fixed now. Please let me know if it isn't.

**Comment by xvdp** [comment]
thank you @keunhong,
Thank you @keunhong 
I will check it with a fresh clone from your project.

Perhaps when I do that I'll  revisit  https://github.com/google/nerfies/issues/26., I tried to see what was wrong with the warping code, but could not find flaws; the subject was perfectly static ( I've scanned lots of people in my life, so I'm sure of that) and when removing the warp option it makes a beautiful RF.
