### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by flynnamy** [google/nerfies#3]
Could you please share one dataset to train and render video? @keunhong

**Comment by keunhong** [comment]
We'll release something soon. Please hang tight. Thanks.

**Comment by LiuXinqi12** [comment]
Could you please share one dataset to facilitate training and rendering results? Thank you very much!  @keunhong

**Comment by keunhong** [comment]
We're currently looking into the process for releasing datasets. Please bear with us--thanks!

**Comment by SikanderBinMukaram** [comment]
Are you planning to release the dataset anytime soon?

**Comment by keunhong** [comment]
Sorry for the delay. We've [released out dataset](https://github.com/google/nerfies/releases/tag/0.1).
