### ISSUE TITLE
Nerfies_Training.ipynb collab fails on model initialization

### ISSUE THREAD

**Issue by yuhufeng** [google/nerfies#30]
I ran both collabs in sequence Nerfies_Capture_Processing.ipynb and Nerfies_Training.ipynb
but on the process of running the second one I just met an error with having changed nothing
This project is great sincerely , but  maybe I need some help to get it run in the right way.
thanks a lot
-----------------------------------------------------------------------------------------------
learning_rate_sched = schedules.from_config(train_config.lr_schedule) 

KeyError                                  Traceback (most recent call last)
<ipython-input-8-5b46b14de6c4> in <module>()
     16 devices_to_use = jax.devices()
     17 
---> 18 learning_rate_sched = schedules.from_config(train_config.lr_schedule)
     19 warp_alpha_sched = schedules.from_config(train_config.warp_alpha_schedule)
     20 elastic_loss_weight_sched = schedules.from_config(

1 frames
/usr/local/lib/python3.7/dist-packages/nerfies/schedules.py in from_config(schedule)
     41     return from_tuple(schedule)
     42   if isinstance(schedule, collections.Mapping):
---> 43     return from_dict(schedule)
     44 
     45   raise ValueError(f'Unknown type {type(schedule)}.')

/usr/local/lib/python3.7/dist-packages/nerfies/schedules.py in from_dict(d)
     31 def from_dict(d):
     32   d = copy.copy(dict(d))
---> 33   schedule_type = d.pop('type')
     34   return SCHEDULE_MAP[schedule_type](**d)
     35 

KeyError: 'type'

**Comment by keunhong** [comment]
Hi, can you let me know which config you are using?
