### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by WangDeyao** [google/nerfies#31]
Hey!

I would like to know approximately how long does "gpu_quarterhd_4gpu.gin" settings take to train? I use 4 1080Ti GPU.

It is 500k iterations, curl dataset 4x (612, 816), batch size 3072, network width 256, both coarse/fine samples 128.

I am asking this because I have to turn off an XLA flag when using JAX due to an old cuda driver version ([issue](https://github.com/google/jax/issues/5723)). I want to know how much slower I am now... It took me 24 hours to run 165K training iterations (~100s for 200 it.). I want to know if it is a normal training speed...

In appendix G of the paper, the HALF experiment is kind of similar. It is 100k iterations, 8 V100 GPU, batch size 8096, both coarse/fine samples 128, but network width only 128, which took only 16 hours. I think maybe the XLA flag does not make me slow significantly?

Thanks!

**Comment by keunhong** [comment]
Hi, IIRC it took around 16 hours in 8x V100s. I'm not sure how long it would take on 4x 1080Ti's unfortunately.
