### ISSUE TITLE
[Fixed]. NameError: name 'triangulate_points' is not defined

### ISSUE THREAD

**Issue by oo92** [google/nerfies#33]
Hi. In the Nerfies Capture Processing notebook, the _Normalize scene based on landmarks._ is throwing the name error for the function "triangulate_points". 

`new_landmark_points = triangulate_points(landmarks_pixels, new_cameras)`

Its supposed to be `triangulate_landmarks()`

**Comment by keunhong** [comment]
Oops, thanks for the fix! Fixed in 8c30643d5598713dac83b4432214f695567075e3
