### ISSUE TITLE
Output depth maps?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [google/nerfies#5]

**Comment by noobtoob4lyfe** [comment]
Thanks for letting us try this out!
Is there a way to use the colab demo to output just depth maps from the position and orientation of the original images?  Not the depth maps from the perspective of the virtual cameras.

**Comment by keunhong** [comment]
You can get the cameras of the original images through the datasource e.g., 
```
camera = datasource.load_camera('000001')
```

see [this line](https://github.com/google/nerfies/blob/main/nerfies/datasets/nerfies.py#L149) for the code.
