### ISSUE TITLE
how to use on video that does not contain a face?

### ISSUE THREAD

**Issue by kurtjcu** [google/nerfies#8]
Hi,
Currently the pre processing notebook for dataset generation is limited to being used with videos that contain faces despite this being marked as an "optional" step.

the mediapipe library is used to get a mesh of the face and parts of this are used to generate the scene.json as well as the test camera path.  

Do you have a more generic workflow or simplified method for generating the scene.json?

**Comment by kurtjcu** [comment]
similar to https://github.com/google/nerfies/issues/2 #

**Comment by keunhong** [comment]
This should be pretty simple:
1. Skip the face section of the Colab and just set `new_scene_manager = scene_manager`.
2. You need to set the scene scale some other way. For example, you can scale it manually or you can compute the radius of the point cloud and set it based on that.
3. The near/far plane logic should be the same.

The test camera trajectory generation won't work without a face so you'll have to manually create your own.

**Comment by kurtjcu** [comment]
I have a stripped back version of the dataset processing that should be pretty generic this may help someone else out there,. https://colab.research.google.com/gist/kurtjcu/887c9e77fbc4434b943da3a75deb47a1/nerfies_still_capture_processing.ipynb

**Comment by ethanyanjiali** [comment]
Thanks @kurtjcu your notebook helps a lot

**Comment by keunhong** [comment]
Hi, I have made the face processing part completely optional by generating camera trajectories without the facial landmarks. Please let me know if you have issues. Thanks!
